version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
    
      - DB_NAME=buys
      - DB_USER=root
      - DB_PASSWORD=toor

  # db:
  #   image: postgres:alpine
  #   container_name: buys_db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: toor
  #     POSTGRES_DB: buys

  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  db:
    image: mariadb:10.6.4
    container_name: buys_db
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=toor
     - MYSQL_DATABASE=buys
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80" # Port for accessing phpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
      
volumes:
   mysql-data:
